

//
// Autogenerated by gaxb at 12:38:35 PM on 04/22/14
//

using System;
using System.Xml;
using System.Text;
using System.Reflection;
using System.Collections.Generic;

public class PlanetUnity_EntityBase : PlanetUnity_ObservableObject {

	private Type planetOverride = Type.GetType("PlanetUnityOverride");



	// XML Attributes
	public cRect bounds;
	public bool boundsExists;

	public bool hidden;
	public bool hiddenExists;

	public float lastY;
	public bool lastYExists;

	public float lastX;
	public bool lastXExists;





	public new void gaxb_load(XmlReader reader, object _parent)
	{
		base.gaxb_load(reader, _parent);


		parent = _parent;
		
		if(this.GetType() == typeof( PlanetUnity_Entity ))
		{
			if(parent != null)
			{
				FieldInfo parentField = _parent.GetType().GetField("Entitys");
				List<object> parentChildren = null;
				if(parentField != null)
				{
					parentChildren = (List<object>)(parentField.GetValue(_parent));
				}
				if(parentChildren == null)
				{
					parentChildren = (List<object>)(_parent.GetType().GetField("children").GetValue(_parent));
				}
				if(parentChildren != null)
				{
					parentChildren.Add(this);
				}
			}
		}
		
		xmlns = reader.GetAttribute("xmlns");
		

		string attr;
		attr = reader.GetAttribute("bounds");
		if(attr != null && planetOverride != null) { attr = planetOverride.GetMethod("processString", BindingFlags.Public | BindingFlags.Static).Invoke(null, new [] {_parent, attr}).ToString(); }
		if(attr != null) { bounds = attr; boundsExists = true; } 
		
		attr = reader.GetAttribute("hidden");
		if(attr != null && planetOverride != null) { attr = planetOverride.GetMethod("processString", BindingFlags.Public | BindingFlags.Static).Invoke(null, new [] {_parent, attr}).ToString(); }
		if(attr != null) { hidden = bool.Parse(attr); hiddenExists = true; } 
		
		attr = reader.GetAttribute("lastY");
		if(attr != null && planetOverride != null) { attr = planetOverride.GetMethod("processString", BindingFlags.Public | BindingFlags.Static).Invoke(null, new [] {_parent, attr}).ToString(); }
		if(attr != null) { lastY = float.Parse(attr); lastYExists = true; } 
		
		attr = reader.GetAttribute("lastX");
		if(attr != null && planetOverride != null) { attr = planetOverride.GetMethod("processString", BindingFlags.Public | BindingFlags.Static).Invoke(null, new [] {_parent, attr}).ToString(); }
		if(attr != null) { lastX = float.Parse(attr); lastXExists = true; } 
		

	}
	
	
	
	
	
	
	
	public new void gaxb_appendXMLAttributes(StringBuilder sb)
	{
		base.gaxb_appendXMLAttributes(sb);

		if(boundsExists) { sb.AppendFormat (" {0}=\"{1}\"", "bounds", bounds); }
		if(hiddenExists) { sb.AppendFormat (" {0}=\"{1}\"", "hidden", hidden.ToString().ToLower()); }
		if(lastYExists) { sb.AppendFormat (" {0}=\"{1}\"", "lastY", lastY); }
		if(lastXExists) { sb.AppendFormat (" {0}=\"{1}\"", "lastX", lastX); }

	}
	
	public new void gaxb_appendXMLSequences(StringBuilder sb)
	{
		base.gaxb_appendXMLSequences(sb);


	}
	
	public new void gaxb_appendXML(StringBuilder sb)
	{
		if(sb.Length == 0)
		{
			sb.AppendFormat ("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
		}
		
		sb.AppendFormat ("<{0}", "Entity");
		
		if(xmlns != null)
		{
			sb.AppendFormat (" {0}=\"{1}\"", "xmlns", xmlns);
		}
		
		gaxb_appendXMLAttributes(sb);
		
		
		StringBuilder seq = new StringBuilder();
		seq.AppendFormat(" ");
		gaxb_appendXMLSequences(seq);
		
		if(seq.Length == 1)
		{
			sb.AppendFormat (" />");
		}
		else
		{
			sb.AppendFormat (">{0}</{1}>", seq.ToString(), "Entity");
		}
	}
}
